# Configuração básica
baseURL = "https://example.com"
theme = "hugo-bearcub"
copyright = "othiagob (CC BY 4.0)"
defaultContentLanguage = "pt"

# Gera robots.txt para SEO
enableRobotsTXT = true

# Configuração de realce de sintaxe sem estilos inline
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.pt]
    title = "OTHIAGOB"
    languageName = "pt-BR 🇧🇷"
    LanguageCode = "pt-BR"
    contentDir = "content.pt"
    [languages.pt.params]
      madeWith = "Feito com [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
  description = "Blog do OTHIAGOB"
  favicon = "images/favicon.png"
  images = ["images/share.webp"]
  title = "OTHIAGOB"
  dateFormat = "2006-01-02"
  hideUntranslated = false
  themeStyle = "original"
  generateSocialCard = true

  [params.author]
    name = "OTHIAGOB"
    email = ""
